### ISSUE TITLE
in validateDigestValue(digest, expectedDigest): TypeError because process.version does not match regex

### ISSUE THREAD

**Issue by paddor** [node-saml/xml-crypto#270] opened 2022-11-22 12:40 UTC
I'm using saml2-js (loaded via ember-browserify 1.2.2) to implement a SAML2 login in an Ember app. When it comes to validating an XML signature, the function `validateDigestValue(digest, expectedDigest)` from this library fails because `process.version` is an empty string in my browser (Safari 15.5).

See the `process` object here pane on the right:
<img width="1653" alt="Screenshot 2022-11-22 at 13 39 09" src="https://user-images.githubusercontent.com/8876/203316217-60aa1fab-534a-41e3-9ac0-76be505adc3b.png">

**Comment by cjbarth** [comment] 2023-05-29 17:58
`process.version` is a Node-only setting (https://nodejs.org/api/process.html#processversion). This library has Node dependencies. See #87 for getting this to work in a browser. Pull requests are welcome.

Duplicate of #87

**Closed by cjbarth** 2023-05-29 17:58 UTC
