### ISSUE TITLE
support XAdES

### ISSUE THREAD

**Issue by bjrmatos** [node-saml/xml-crypto#89] opened 2016-02-14 01:51 UTC
related to #61 

reference: https://xadesnet.codeplex.com/

**Comment by rmhrisk** [comment] 2016-02-14 03:10
This is also a good reference https://www.microsoft.com/france/openness/open-source/interoperabilite_xades.aspx

**Comment by rmhrisk** [comment] 2016-05-06 00:34
We have built on this excellent library and have the foundation for XAdES here : https://www.npmjs.com/package/xadesjs

**Comment by LoneRifle** [comment] 2023-05-28 13:40
Duplicate of #87

**Closed by LoneRifle** 2023-05-28 13:40 UTC
Labels: feature-request

**Comment by GauriSpears** [comment] 2023-09-04 10:11
So is there a way to add <Object><QualifyingProperties>... **after** KeyInfo? All I see is to add something **into** KeyInfo with keyInfoAttributes property.

**Comment by GauriSpears** [comment] 2023-09-05 21:32
UPD: I overrode getKeyInfo to successfully add xades object definition after KeyInfo node. Thanks for xml-crypto! It's VERY customizable!
